name: build
on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build a Test Image
        id: image_build
        run: |
          docker build --no-cache --file tests/Dockerfile --tag uptycs-action-test:local --iidfile=image_id.out .
          echo ::set-output name=image_id::$(docker images -q uptycs-action-test:local)

      - name: Run Uptycs Vulnerability Scanner
        uses: uptycslabs/uptycs-action@add-action
        with:
          uptycs-secret: ${{ secrets.UPTYCS_SECRET }}
          osquery-flags: ${{ secrets.OSQUERY_FLAGS }}
          image-id: ${{ steps.image_build.outputs.image_id }}
